import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Mode = "generate" | "edit" | "gallery" | "settings";
type Output = { id: string; b64: string; createdAt: number; galleryId?: string; prompt?: string; model?: string; size?: string; quality?: string; ratio?: string; resolution?: string };
type RunOverride = { prompt?: string; mode?: "generate" | "edit"; size?: string; quality?: string; ratio?: string; resolution?: string; image?: File | null; mask?: File | null };

const resolutionOptions = [{ value: "1k", label: "1K（标准）" }, { value: "2k", label: "2K（高清）" }, { value: "4k", label: "4K（超清）" }];
const ratioOptions = [{ value: "1:1", label: "1:1 正方形" }, { value: "4:3", label: "4:3 横向" }, { value: "3:4", label: "3:4 竖向" }, { value: "3:2", label: "3:2 横向" }, { value: "2:3", label: "2:3 竖向" }, { value: "16:9", label: "16:9 宽屏" }, { value: "9:16", label: "9:16 手机" }, { value: "4:5", label: "4:5 人像" }, { value: "5:4", label: "5:4 横幅" }, { value: "21:9", label: "21:9 超宽" }];
const sizeMatrix: Record<string, Record<string, string>> = { "1k": { "1:1": "1024x1024", "4:3": "1024x768", "3:4": "768x1024", "3:2": "1536x1024", "2:3": "1024x1536", "16:9": "1536x864", "9:16": "864x1536", "4:5": "1024x1280", "5:4": "1280x1024", "21:9": "1536x656" }, "2k": { "1:1": "2048x2048", "4:3": "2048x1536", "3:4": "1536x2048", "3:2": "2048x1360", "2:3": "1360x2048", "16:9": "2048x1152", "9:16": "1152x2048", "4:5": "1632x2048", "5:4": "2048x1632", "21:9": "2048x880" }, "4k": { "1:1": "2880x2880", "4:3": "3328x2480", "3:4": "2480x3328", "3:2": "3520x2352", "2:3": "2352x3520", "16:9": "3840x2160", "9:16": "2160x3840", "4:5": "2560x3200", "5:4": "3200x2560", "21:9": "3840x1648" } };
const qualities = [{ value: "auto", label: "自动" }, { value: "low", label: "快速草图" }, { value: "medium", label: "标准" }, { value: "high", label: "最高细节" }];

function fileToPayload(file: File) { return new Promise<{ name: string; type: string; data: number[] }>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, type: file.type, data: Array.from(new Uint8Array(reader.result as ArrayBuffer)) }); reader.onerror = () => reject(reader.error); reader.readAsArrayBuffer(file); }); }
function b64ToFile(b64: string, name: string) { const bytes = Uint8Array.from(atob(b64), char => char.charCodeAt(0)); return new File([bytes], name, { type: "image/png" }); }

function App() {
  const [mode, setMode] = useState<Mode>("generate"); const [prompt, setPrompt] = useState(""); const [quality, setQuality] = useState("auto"); const [resolution, setResolution] = useState("1k"); const [ratio, setRatio] = useState("1:1"); const [n, setN] = useState(1);
  const [image, setImage] = useState<File | null>(null); const [mask, setMask] = useState<File | null>(null); const [outputs, setOutputs] = useState<Output[]>([]); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState<AppProgress | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [configured, setConfigured] = useState(false); const [apiKey, setApiKey] = useState(""); const [baseUrl, setBaseUrl] = useState("https://api.pinaic.com/v1"); const [autoArchive, setAutoArchive] = useState(true); const [testMessage, setTestMessage] = useState(""); const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const [templates, setTemplates] = useState<PromptTemplate[]>([]); const [selectedTemplate, setSelectedTemplate] = useState(""); const [galleryItems, setGalleryItems] = useState<GalleryItem[]>([]); const [galleryThumbs, setGalleryThumbs] = useState<Record<string, string>>({}); const [galleryQuery, setGalleryQuery] = useState(""); const [favoriteOnly, setFavoriteOnly] = useState(false); const [gallerySort, setGallerySort] = useState<"newest" | "oldest">("newest"); const [preview, setPreview] = useState<Output | null>(null);
  const chosenSize = sizeMatrix[resolution][ratio];

  useEffect(() => { window.pinaic.settings.get().then(value => { setConfigured(value.configured); setBaseUrl(value.baseUrl); setAutoArchive(value.autoArchive); }); window.pinaic.templates.list().then(value => setTemplates(value.items)); return window.pinaic.onProgress(value => { if (value.requestId === requestId) setProgress(value); }); }, [requestId]);
  useEffect(() => { if (mode === "gallery") window.pinaic.gallery.search({ query: galleryQuery, favoriteOnly, sort: gallerySort }).then(value => setGalleryItems(value.items)); }, [mode, galleryQuery, favoriteOnly, gallerySort]);
  useEffect(() => { if (mode !== "gallery") return; Promise.all(galleryItems.map(async item => [item.id, (await window.pinaic.gallery.loadImage(item.id)).b64 || ""] as const)).then(items => setGalleryThumbs(Object.fromEntries(items.filter(([, b64]) => b64)))); }, [mode, galleryItems]);

  const applyTemplate = (id: string) => { const item = templates.find(value => value.id === id); if (!item) return; setSelectedTemplate(id); setPrompt(item.prompt); if (item.ratio && ratioOptions.some(value => value.value === item.ratio)) setRatio(item.ratio); if (item.resolution && sizeMatrix[item.resolution]) setResolution(item.resolution); if (item.quality) setQuality(item.quality); setMode("generate"); };
  const saveTemplate = async () => { if (!prompt.trim()) { setError("请先输入提示词再保存模板"); return; } const title = window.prompt("模板名称", "我的模板"); if (!title?.trim()) return; const result = await window.pinaic.templates.save({ title, category: "自定义", prompt, ratio, resolution, quality }); if (result.item) { setTemplates(current => [...current.filter(item => item.id !== result.item!.id), result.item!]); setSelectedTemplate(result.item.id); setNotice("模板已保存"); } };
  const editTemplate = async () => { const item = templates.find(value => value.id === selectedTemplate); if (!item || item.builtin) return; const title = window.prompt("模板名称", item.title); if (!title?.trim()) return; const result = await window.pinaic.templates.save({ ...item, title, prompt, ratio, resolution, quality }); if (result.item) { setTemplates(current => current.map(value => value.id === result.item!.id ? result.item! : value)); setNotice("模板已更新"); } };
  const deleteTemplate = async () => { const item = templates.find(value => value.id === selectedTemplate); if (!item || item.builtin || !window.confirm(`删除模板“${item.title}”吗？`)) return; await window.pinaic.templates.delete(item.id); setTemplates(current => current.filter(value => value.id !== item.id)); setSelectedTemplate(""); };

  const run = async (override: RunOverride = {}) => {
    const activeMode = override.mode || (mode === "edit" ? "edit" : "generate"); const activePrompt = (override.prompt ?? prompt).trim(); const activeResolution = override.resolution || resolution; const activeRatio = override.ratio || ratio; const activeSize = override.size || sizeMatrix[activeResolution][activeRatio]; const activeQuality = override.quality || quality; const activeImage = override.image === undefined ? image : override.image; const activeMask = override.mask === undefined ? mask : override.mask;
    if (!activePrompt) { setError("请先输入提示词"); return; } if (activeMode === "edit" && !activeImage) { setError("编辑模式需要上传原图"); return; } if (!configured) { setError("请先到设置页保存 API 密钥"); return; }
    const id = crypto.randomUUID(); setRequestId(id); setError(""); setNotice(""); setBusy(true); setProgress({ requestId: id, status: "准备请求", progress: 0 });
    try {
      const ratioPrompt = `\n\n构图要求：严格使用 ${activeRatio} 画面比例（${activeSize} 像素画布）进行原生构图；不要生成正方形，不要在生成后裁切；主体、文字和边缘内容必须完整适配画布。`; const common = { requestId: id, prompt: `${activePrompt}${ratioPrompt}`, model: "gpt-image-2", size: activeSize, n: activeMode === "edit" ? 1 : n, quality: activeQuality, ratio: activeRatio, resolution: activeResolution };
      const result = activeMode === "edit" ? await window.pinaic.edit({ ...common, image: await fileToPayload(activeImage!), mask: activeMask ? await fileToPayload(activeMask) : undefined }) : await window.pinaic.generate(common); if (!result.ok) throw new Error(result.error || "生成失败");
      const seen = new Set<string>(); const gallery = result.gallery || []; const unique = (result.images || []).filter(item => { if (!item.b64_json || seen.has(item.b64_json)) return false; seen.add(item.b64_json); return true; }).slice(0, activeMode === "edit" ? 1 : n);
      setOutputs(unique.map((item, index) => ({ id: crypto.randomUUID(), b64: item.b64_json!, createdAt: Date.now(), galleryId: gallery[index]?.id, prompt: activePrompt, model: "gpt-image-2", size: activeSize, quality: activeQuality, ratio: activeRatio, resolution: activeResolution })));
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  const cancel = () => { if (busy) window.pinaic.cancel(requestId); };
  const save = async (output: Output) => { const result = await window.pinaic.saveImage({ dataUrl: `data:image/png;base64,${output.b64}`, suggestedName: `pinaic-${new Date(output.createdAt).toISOString().replace(/[:.]/g, "-")}.png` }); if (!result.canceled) setNotice(`已保存：${result.path}`); };
  const regenerate = (output: Output) => { setPrompt(output.prompt || prompt); setResolution(output.resolution || resolution); setRatio(output.ratio || ratio); setQuality(output.quality || quality); run({ prompt: output.prompt, size: output.size, ratio: output.ratio, resolution: output.resolution, quality: output.quality, mode: "generate" }); };
  const continueEdit = (output: Output) => { setMode("edit"); setPrompt(output.prompt || ""); setImage(b64ToFile(output.b64, "pinaic-source.png")); setRatio(output.ratio || ratio); setResolution(output.resolution || resolution); setQuality(output.quality || quality); setNotice("已带入原图，可修改提示词后继续编辑"); };
  const saveSettings = async () => { if (!apiKey.trim() && !configured) { setError("请输入 API 密钥"); return; } await window.pinaic.settings.save({ apiKey, baseUrl, autoArchive }); setConfigured(true); setApiKey(""); setNotice("设置已保存"); };
  const testSettings = async () => { setTestMessage("测试中…"); const result = await window.pinaic.settings.test(); setTestMessage(result.message); };
  const galleryOutput = async (item: GalleryItem) => { const result = await window.pinaic.gallery.loadImage(item.id); return result.b64 ? { id: item.id, b64: result.b64, createdAt: Date.parse(item.createdAt), galleryId: item.id, prompt: item.prompt, model: item.model, size: item.size, quality: item.quality, ratio: item.ratio, resolution: item.resolution } as Output : null; };
  const loadPreview = async (item: GalleryItem) => { const output = await galleryOutput(item); if (output) setPreview(output); };
  const reuseGallery = async (item: GalleryItem, edit: boolean) => { const output = await galleryOutput(item); if (!output) return; if (edit) continueEdit(output); else { setMode("generate"); setPrompt(item.prompt); if (item.ratio) setRatio(item.ratio); if (item.resolution) setResolution(item.resolution); if (item.quality) setQuality(item.quality); setNotice("已复用图库参数，可修改提示词后生成"); } };
  const toggleFavorite = async (item: GalleryItem) => { await window.pinaic.gallery.toggleFavorite(item.id); const result = await window.pinaic.gallery.search({ query: galleryQuery, favoriteOnly, sort: gallerySort }); setGalleryItems(result.items); };
  const deleteGallery = async (item: GalleryItem) => { if (!window.confirm("删除这条图库记录及对应图片文件吗？")) return; await window.pinaic.gallery.delete(item.id); setGalleryItems(current => current.filter(value => value.id !== item.id)); };

  const templateBar = <div className="prompt-tools"><label>提示词模板<select value={selectedTemplate} onChange={e => applyTemplate(e.target.value)}><option value="">选择模板…</option>{templates.map(item => <option key={item.id} value={item.id}>[{item.category}] {item.title}</option>)}</select></label><button className="secondary" onClick={saveTemplate}>保存为模板</button>{selectedTemplate && !templates.find(item => item.id === selectedTemplate)?.builtin && <><button className="secondary" onClick={editTemplate}>编辑模板</button><button className="secondary" onClick={deleteTemplate}>删除模板</button></>}</div>;
  const generatorPanel = <section className="card composer"><div className="mode-title"><div><span className="eyebrow">{mode === "edit" ? "IMAGE EDIT" : "TEXT TO IMAGE"}</span><h2>{mode === "edit" ? "编辑一张图片" : "描述你想要的画面"}</h2></div><span className="pill">{mode === "edit" ? "保持主体 · 修改场景" : "自然语言提示词"}</span></div>{templateBar}<textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder={mode === "edit" ? "例如：保持主体不变，把背景改成未来城市夜景" : "例如：一张科技感产品海报，蓝白配色，干净高级"} rows={5} />{mode === "edit" && <div className="upload-row"><label className="upload">{image ? `原图：${image.name}` : "上传原图"}<input type="file" accept="image/*" onChange={e => setImage(e.target.files?.[0] || null)} /></label><label className="upload ghost">{mask ? `蒙版：${mask.name}` : "可选蒙版"}<input type="file" accept="image/*" onChange={e => setMask(e.target.files?.[0] || null)} /></label></div>}<div className="controls"><label>细节质量<select value={quality} onChange={e => setQuality(e.target.value)}>{qualities.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>清晰度<select value={resolution} onChange={e => setResolution(e.target.value)}>{resolutionOptions.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>画面比例<select value={ratio} onChange={e => setRatio(e.target.value)}>{ratioOptions.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>数量<select value={n} onChange={e => setN(Number(e.target.value))}>{[1, 2, 3, 4].map(value => <option key={value} value={value}>{value} 张</option>)}</select></label></div><p className="size-hint">当前输出：{chosenSize} · {ratio} 比例 · {resolution.toUpperCase()} 清晰度</p><div className="run-row"><button className="primary generate" onClick={() => run()} disabled={busy}>{busy ? "生成中…" : mode === "edit" ? "开始编辑" : "开始生成"}</button>{busy && <button className="secondary" onClick={cancel}>取消</button>}<span className="save-note">自动归档：{autoArchive ? "已开启" : "已关闭"}</span></div>{progress && busy && <div className="progress"><div className="progress-track"><div style={{ width: `${progress.progress ?? 12}%` }} /></div><span>{progress.status}{progress.message ? ` · ${progress.message}` : ""}</span></div>}</section>;
  const resultPanel = <section className="card results"><div className="section-head"><div><span className="eyebrow">RESULTS</span><h2>生成结果</h2></div>{outputs.length > 0 && <span className="muted">{outputs.length} 张图片 · 点击图片查看大图</span>}</div>{error && <div className="error">{error}</div>}{notice && <div className="notice">{notice}</div>}{outputs.length === 0 ? <div className="empty"><span>✧</span><p>生成后的图片会显示在这里</p><small>模板、图库和迭代操作会保留你的创作过程</small></div> : <div className="gallery">{outputs.map(output => <article key={output.id}><img className="result-image" onClick={() => setPreview(output)} src={`data:image/png;base64,${output.b64}`} /><div className="result-actions"><button onClick={() => save(output)}>保存 PNG</button><button onClick={() => regenerate(output)}>再生成</button><button onClick={() => continueEdit(output)}>继续编辑</button></div></article>)}</div>}</section>;
  const galleryPanel = <section className="card gallery-workspace"><div className="section-head"><div><span className="eyebrow">LOCAL GALLERY</span><h2>本地图库</h2></div><span className="muted">自动归档到 保存图片\图库</span></div><div className="gallery-filters"><input value={galleryQuery} onChange={e => setGalleryQuery(e.target.value)} placeholder="搜索提示词、模型或尺寸" /><label className="check"><input type="checkbox" checked={favoriteOnly} onChange={e => setFavoriteOnly(e.target.checked)} /> 只看收藏</label><label className="sort-control">排序<select value={gallerySort} onChange={e => setGallerySort(e.target.value as "newest" | "oldest")}><option value="newest">最新优先</option><option value="oldest">最早优先</option></select></label></div>{galleryItems.length === 0 ? <div className="empty"><span>▧</span><p>还没有归档图片</p><small>生成图片后会自动出现在这里</small></div> : <div className="gallery archive-grid">{galleryItems.map(item => <article key={item.id}><button className="archive-preview" onClick={() => loadPreview(item)}>{galleryThumbs[item.id] ? <img src={`data:image/png;base64,${galleryThumbs[item.id]}`} alt="" /> : <span>加载预览…</span>}<span>点击查看大图</span></button><div className="archive-meta"><strong>{new Date(item.createdAt).toLocaleString()}</strong><small>{item.size} · {item.model}</small><p>{item.prompt}</p></div><div className="result-actions"><button onClick={() => loadPreview(item)}>预览</button><button onClick={() => reuseGallery(item, false)}>复用</button><button onClick={() => reuseGallery(item, true)}>继续编辑</button><button onClick={() => toggleFavorite(item)}>{item.favorite ? "取消收藏" : "收藏"}</button><button onClick={() => deleteGallery(item)}>删除</button></div></article>)}</div>}</section>;
  return <div className="app"><header><div><span className="eyebrow">PINAI IMAGE STUDIO</span><h1>把想象变成图片</h1><p>本地创作工作台 · 模板、图库与迭代</p></div><div className="status"><i className={configured ? "ok" : "off"}></i>{configured ? "已配置" : "未配置密钥"}</div></header><div className="layout"><aside><button className={mode === "generate" ? "nav active" : "nav"} onClick={() => setMode("generate")}>✦ 文生图</button><button className={mode === "edit" ? "nav active" : "nav"} onClick={() => setMode("edit")}>◌ 图片编辑</button><button className={mode === "gallery" ? "nav active" : "nav"} onClick={() => setMode("gallery")}>▧ 本地图库</button><button className={mode === "settings" ? "nav active" : "nav"} onClick={() => setMode("settings")}>⚙ 设置</button><div className="aside-tip">模型<br /><strong>gpt-image-2</strong><br /><span>支持模板 · 自动归档 · 迭代编辑</span></div></aside><main>{mode === "settings" ? <section className="card settings"><h2>连接设置</h2><p className="muted">密钥只通过 Windows 凭据库保存，不会写入项目文件。</p><label>PinAI API 地址<input value={baseUrl} onChange={e => setBaseUrl(e.target.value)} /></label><label>API 密钥<input type="password" placeholder={configured ? "已保存（输入新值可覆盖）" : "粘贴你的 PinAI API 密钥"} value={apiKey} onChange={e => setApiKey(e.target.value)} /></label><label className="archive-toggle"><input type="checkbox" checked={autoArchive} onChange={e => setAutoArchive(e.target.checked)} /> 自动归档生成图片到本地图库</label><div className="actions"><button className="primary" onClick={saveSettings}>保存设置</button><button className="secondary" onClick={testSettings}>测试连接</button></div>{testMessage && <p className="hint">{testMessage}</p>}</section> : mode === "gallery" ? galleryPanel : <>{generatorPanel}{resultPanel}</>}</main></div>{preview && <div className="lightbox" onClick={() => setPreview(null)}><button className="lightbox-close" onClick={() => setPreview(null)} aria-label="关闭预览">×</button><img src={`data:image/png;base64,${preview.b64}`} onClick={event => event.stopPropagation()} /><span>点击空白处或右上角关闭</span></div>}</div>;
}

createRoot(document.getElementById("root")!).render(<App />);
